plugins { id 'com.android.application' }

android {
    namespace 'mg.appmada.baindefrancais'
    compileSdk 35

    defaultConfig {
        applicationId 'mg.appmada.baindefrancais.user2'
        minSdk 23
        targetSdk 35
        versionCode 21
        versionName '2.0.1'
    }

    buildTypes {
        debug {
            debuggable false
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
